/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import model.Product;
import model.ProductAddress;
import model.ProductDoctor;
import model.ProductDriver;
import model.ProductVehicleRegistration;
import model.ProductInsurance;
import model.ProductPatient;

/**
 *
 * @author sanal
 */
public class DisplayReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonJPanel
     */
    Product product;
    ProductAddress productaddress;
    ProductDoctor productdoctor;
    ProductDriver productdriver;
    ProductVehicleRegistration productvehicleregistration;
    ProductInsurance productinsurance;
    ProductPatient productpatient;
    
    public DisplayReportJPanel(Product product, ProductAddress productaddress, ProductDoctor productdoctor, ProductDriver productdriver, ProductVehicleRegistration productvehicleregistration, ProductInsurance productinsurance, ProductPatient productpatient) {
        initComponents();
        this.product = product;
        this.productaddress = productaddress;
        this.productdoctor = productdoctor;
        this.productdriver = productdriver;
        this.productvehicleregistration = productvehicleregistration;
        this.productinsurance = productinsurance;
        this.productpatient = productpatient;
        this.setBackground(new Color(224, 255, 255));
        displayProduct();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitlePerson = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPermAddress = new javax.swing.JLabel();
        lblTempAddress = new javax.swing.JLabel();
        lblOccupation = new javax.swing.JLabel();
        lblNationality = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPermAddress = new javax.swing.JTextField();
        txtTempAddress = new javax.swing.JTextField();
        txtOccupation = new javax.swing.JTextField();
        txtNationality = new javax.swing.JTextField();
        lblNextAppointment = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        lblOnMedication = new javax.swing.JLabel();
        lblInsuranceCoverage = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtPrimaryDoctor = new javax.swing.JTextField();
        txtLastVisit = new javax.swing.JTextField();
        lblTitlePatient = new javax.swing.JLabel();
        txtNextAppointment = new javax.swing.JTextField();
        lblPatientID = new javax.swing.JLabel();
        lblPrimaryDoctor = new javax.swing.JLabel();
        lblLastVisit = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblGPS = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtGPS = new javax.swing.JTextField();
        lblTitleAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblDeductible = new javax.swing.JLabel();
        txtCorporateID = new javax.swing.JTextField();
        txtInsuranceAddress = new javax.swing.JTextField();
        txtPremium = new javax.swing.JTextField();
        txtDeductible = new javax.swing.JTextField();
        lblBenefits = new javax.swing.JLabel();
        lblTitleVehicleRegistration = new javax.swing.JLabel();
        txtBenefits = new javax.swing.JTextField();
        lblCorporateID = new javax.swing.JLabel();
        lblInsuranceAddress = new javax.swing.JLabel();
        lblPremium = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitlePerson2 = new javax.swing.JLabel();
        lblPracticeAddress = new javax.swing.JLabel();
        lblYears = new javax.swing.JLabel();
        txtFirstNameDoctor = new javax.swing.JTextField();
        txtLastNameDoctor = new javax.swing.JTextField();
        txtSpecialization = new javax.swing.JTextField();
        lblFirstNameDoctor = new javax.swing.JLabel();
        txtEducation = new javax.swing.JTextField();
        lblLastNameDoctor = new javax.swing.JLabel();
        txtMedicalLicense = new javax.swing.JTextField();
        lblSpecialization = new javax.swing.JLabel();
        txtDoctorContact = new javax.swing.JTextField();
        lblEducation = new javax.swing.JLabel();
        txtPracticeAddress = new javax.swing.JTextField();
        lblMedicalLicense = new javax.swing.JLabel();
        txtYears = new javax.swing.JTextField();
        lblDoctorContact = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitleDriver = new javax.swing.JLabel();
        lblDriverLicense = new javax.swing.JLabel();
        txtDriverLicense = new javax.swing.JTextField();
        lblTitleVehicleRegistration1 = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblSerialNumber = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblLicenseNumber = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        lblExpirationDate = new javax.swing.JLabel();
        txtExpirationDate = new javax.swing.JTextField();
        comboAllergies = new javax.swing.JComboBox<>();
        comboOnMedication = new javax.swing.JComboBox<>();
        comboInsuranceCoverage = new javax.swing.JComboBox<>();
        lblUploadImage = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORT");

        lblTitlePerson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitlePerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePerson.setText("Personal Information");

        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstName.setText("First Name:");

        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastName.setText("Last Name:");

        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSSN.setText("SSN:");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmail.setText("Email:");

        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDOB.setText("DOB:");

        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone.setText("Phone:");

        lblPermAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPermAddress.setText("Permanent Address:");

        lblTempAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTempAddress.setText("Temporary Address:");

        lblOccupation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOccupation.setText("Occupation:");

        lblNationality.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNationality.setText("Nationality:");

        lblNextAppointment.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNextAppointment.setText("Next Appointment:");

        lblAllergies.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAllergies.setText("Allergies?");

        lblOnMedication.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOnMedication.setText("On Medication?");

        lblInsuranceCoverage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInsuranceCoverage.setText("Insurance Coverage:");

        lblTitlePatient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitlePatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePatient.setText("Medical Information");

        lblPatientID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPatientID.setText("Patient ID:");

        lblPrimaryDoctor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrimaryDoctor.setText("Primary Doctor:");

        lblLastVisit.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastVisit.setText("Last Visit:");

        lblCountry.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCountry.setText("Country:");

        lblGPS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGPS.setText("GPS:");

        lblTitleAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleAddress.setText("Address Information");

        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCity.setText("City:");

        lblState.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblState.setText("State:");

        lblDeductible.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDeductible.setText("Deductible:");

        lblBenefits.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBenefits.setText("Benefits:");

        lblTitleVehicleRegistration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleVehicleRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleVehicleRegistration.setText("Insurance Information");

        lblCorporateID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCorporateID.setText("Corporate ID:");

        lblInsuranceAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInsuranceAddress.setText("Address:");

        lblPremium.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPremium.setText("Premium:");

        lblTitlePerson2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitlePerson2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePerson2.setText("Doctor Information");

        lblPracticeAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPracticeAddress.setText("Practice Address:");

        lblYears.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblYears.setText("Years Of Practice:");

        lblFirstNameDoctor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstNameDoctor.setText("First Name:");

        lblLastNameDoctor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastNameDoctor.setText("Last Name:");

        lblSpecialization.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSpecialization.setText("Specialization:");

        lblEducation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEducation.setText("Education:");

        lblMedicalLicense.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMedicalLicense.setText("Medical License:");

        lblDoctorContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDoctorContact.setText("Doctor Contact:");

        lblTitleDriver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDriver.setText("Driver");

        lblDriverLicense.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDriverLicense.setText("Driver License:");

        lblTitleVehicleRegistration1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleVehicleRegistration1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleVehicleRegistration1.setText("Vehicle Registration");

        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblModel.setText("Model:");

        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSerialNumber.setText("Serial Number:");

        lblLicenseNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicenseNumber.setText("License Number:");

        lblExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblExpirationDate.setText("Expiration Date:");

        comboAllergies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No"}));
        comboAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAllergiesActionPerformed(evt);
            }
        });

        comboOnMedication.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No"}));
        comboOnMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOnMedicationActionPerformed(evt);
            }
        });

        comboInsuranceCoverage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No"}));
        comboInsuranceCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInsuranceCoverageActionPerformed(evt);
            }
        });

        lblUploadImage.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblUploadImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUploadImage.setText("Upload An Image");
        lblUploadImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitleAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(88, 88, 88))
                            .addComponent(lblTitlePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblState)
                                            .addComponent(lblCity)
                                            .addComponent(lblCountry)
                                            .addComponent(lblGPS))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLastName)
                                            .addComponent(lblFirstName)
                                            .addComponent(lblSSN)
                                            .addComponent(lblEmail)
                                            .addComponent(lblDOB)
                                            .addComponent(lblPhone)
                                            .addComponent(lblPermAddress)
                                            .addComponent(lblTempAddress)
                                            .addComponent(lblOccupation)
                                            .addComponent(lblNationality))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPermAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTempAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInsuranceAddress)
                                    .addComponent(lblCorporateID)
                                    .addComponent(lblPremium)
                                    .addComponent(lblDeductible)
                                    .addComponent(lblBenefits))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInsuranceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeductible, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTitleVehicleRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitlePatient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPrimaryDoctor)
                                            .addComponent(lblPatientID)
                                            .addComponent(lblLastVisit)
                                            .addComponent(lblNextAppointment)
                                            .addComponent(lblAllergies))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPatientID)
                                            .addComponent(txtPrimaryDoctor)
                                            .addComponent(txtLastVisit)
                                            .addComponent(txtNextAppointment)
                                            .addComponent(comboAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblInsuranceCoverage)
                                            .addComponent(lblOnMedication))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblSerialNumber)
                                            .addComponent(lblModel)
                                            .addComponent(lblLicenseNumber)
                                            .addComponent(lblExpirationDate))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(171, 171, 171)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTitleVehicleRegistration1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1046, 1046, 1046))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(lblDriverLicense)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(192, 192, 192))
                                            .addComponent(lblTitleDriver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitlePerson2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLastNameDoctor)
                                            .addComponent(lblFirstNameDoctor)
                                            .addComponent(lblSpecialization)
                                            .addComponent(lblEducation)
                                            .addComponent(lblMedicalLicense)
                                            .addComponent(lblDoctorContact)
                                            .addComponent(lblPracticeAddress)
                                            .addComponent(lblYears))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMedicalLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDoctorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPracticeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFirstNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLastNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(48, 48, 48)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitlePerson2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstNameDoctor)
                            .addComponent(txtFirstNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastNameDoctor)
                            .addComponent(txtLastNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSpecialization)
                            .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEducation)
                            .addComponent(txtEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedicalLicense)
                            .addComponent(txtMedicalLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDoctorContact)
                            .addComponent(txtDoctorContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPracticeAddress)
                            .addComponent(txtPracticeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYears)
                            .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTitleDriver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDriverLicense)
                                    .addComponent(txtDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTitleVehicleRegistration1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModel)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSerialNumber)
                                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLicenseNumber)
                                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblExpirationDate)
                                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblTitlePatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrimaryDoctor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastVisit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNextAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNextAppointment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAllergies)
                            .addComponent(comboAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOnMedication)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblInsuranceCoverage))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleVehicleRegistration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorporateID)
                            .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInsuranceAddress)
                            .addComponent(txtInsuranceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPremium)
                            .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitlePerson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDOB)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPermAddress)
                            .addComponent(txtPermAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTempAddress)
                            .addComponent(txtTempAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOccupation)
                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNationality)
                            .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblTitleAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblState)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCountry)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGPS)
                            .addComponent(txtGPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeductible)
                    .addComponent(txtDeductible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBenefits)
                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1586, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAllergiesActionPerformed

    private void comboOnMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOnMedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOnMedicationActionPerformed

    private void comboInsuranceCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInsuranceCoverageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboInsuranceCoverageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboAllergies;
    private javax.swing.JComboBox<String> comboInsuranceCoverage;
    private javax.swing.JComboBox<String> comboOnMedication;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCorporateID;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeductible;
    private javax.swing.JLabel lblDoctorContact;
    private javax.swing.JLabel lblDriverLicense;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstNameDoctor;
    private javax.swing.JLabel lblGPS;
    private javax.swing.JLabel lblInsuranceAddress;
    private javax.swing.JLabel lblInsuranceCoverage;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastNameDoctor;
    private javax.swing.JLabel lblLastVisit;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblMedicalLicense;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblNextAppointment;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblOnMedication;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPermAddress;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPracticeAddress;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTempAddress;
    private javax.swing.JLabel lblTitleAddress;
    private javax.swing.JLabel lblTitleDriver;
    private javax.swing.JLabel lblTitlePatient;
    private javax.swing.JLabel lblTitlePerson;
    private javax.swing.JLabel lblTitlePerson2;
    private javax.swing.JLabel lblTitleVehicleRegistration;
    private javax.swing.JLabel lblTitleVehicleRegistration1;
    private javax.swing.JLabel lblUploadImage;
    private javax.swing.JLabel lblYears;
    private javax.swing.JTextField txtBenefits;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCorporateID;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDeductible;
    private javax.swing.JTextField txtDoctorContact;
    private javax.swing.JTextField txtDriverLicense;
    private javax.swing.JTextField txtEducation;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFirstNameDoctor;
    private javax.swing.JTextField txtGPS;
    private javax.swing.JTextField txtInsuranceAddress;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLastNameDoctor;
    private javax.swing.JTextField txtLastVisit;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtMedicalLicense;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtNextAppointment;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPermAddress;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPracticeAddress;
    private javax.swing.JTextField txtPremium;
    private javax.swing.JTextField txtPrimaryDoctor;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtSpecialization;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTempAddress;
    private javax.swing.JTextField txtYears;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        System.out.println("Patient's Address Details");
        
        txtFirstName.setText(product.getFirstname());
        System.out.println("First Name: "+product.getFirstname());
        txtLastName.setText(product.getLastname());
        System.out.println("Last Name: "+product.getLastname());
        txtSSN.setText(product.getSsn());
        System.out.println("SSN: "+product.getSsn());
        txtEmail.setText(product.getEmail());
        System.out.println("Email: "+product.getEmail());
        txtDOB.setText(product.getDob());
        System.out.println("DOB: "+product.getDob());
        txtPhone.setText(product.getPhone());
        System.out.println("Phone: "+product.getPhone());
        txtPermAddress.setText(product.getPermaddress());
        System.out.println("Permanent Address: "+product.getPermaddress());
        txtTempAddress.setText(product.getTempaddress());
        System.out.println("Temporary Address: "+product.getTempaddress());
        txtOccupation.setText(product.getOccupation());
        System.out.println("Occupation: "+product.getOccupation());
        txtNationality.setText(product.getNationality());
        System.out.println("Nationality: "+product.getNationality());
        txtCity.setText(productaddress.getCity());
        System.out.println("City: "+productaddress.getCity());
        txtState.setText(productaddress.getState());
        System.out.println("State: "+productaddress.getState());
        txtCountry.setText(productaddress.getCountry());
        System.out.println("Country: "+productaddress.getCountry());
        txtGPS.setText(productaddress.getGps());
        System.out.println("GPS: "+productaddress.getGps());
        txtFirstNameDoctor.setText(productdoctor.getFirstnamedoctor());
        System.out.println("First Name: "+productdoctor.getFirstnamedoctor());
        txtLastNameDoctor.setText(productdoctor.getLastnamedoctor());
        System.out.println("Last Name: "+productdoctor.getLastnamedoctor());
        txtSpecialization.setText(productdoctor.getSpecialization());
        System.out.println("Specialization: "+productdoctor.getSpecialization());
        txtEducation.setText(productdoctor.getEducation());
        System.out.println("Education: "+productdoctor.getEducation());
        txtMedicalLicense.setText(productdoctor.getMedicallicense());
        System.out.println("Medical License: "+productdoctor.getMedicallicense());
        txtDoctorContact.setText(productdoctor.getDoctorcontact());
        System.out.println("Contact: "+productdoctor.getDoctorcontact());
        txtPracticeAddress.setText(productdoctor.getPracticeaddress());
        System.out.println("Practice Address: "+productdoctor.getPracticeaddress());
        txtYears.setText(productdoctor.getYears());
        System.out.println("Years: "+productdoctor.getYears());
        txtDriverLicense.setText(productdriver.getDriverlicense());
        System.out.println("Driver: "+productdriver.getDriverlicense());
        txtExpirationDate.setText(productvehicleregistration.getExpirationdate());
        System.out.println("Driver: "+productvehicleregistration.getExpirationdate());
        txtModel.setText(productvehicleregistration.getModel());
        System.out.println("Model: "+productvehicleregistration.getModel());
        txtSerialNumber.setText(productvehicleregistration.getSerialnumber());
        System.out.println("Serial Number: "+productvehicleregistration.getSerialnumber());
        txtLicenseNumber.setText(productvehicleregistration.getLicensenumber());
        System.out.println("License Number: "+productvehicleregistration.getLicensenumber());
        txtCorporateID.setText(productinsurance.getCorporateid());
        System.out.println("Corporate ID: "+productinsurance.getCorporateid());
        txtInsuranceAddress.setText(productinsurance.getInsuranceaddress());
        System.out.println("Insurance Address: "+productinsurance.getInsuranceaddress());
        txtPremium.setText(productinsurance.getPremium());
        System.out.println("Premium: "+productinsurance.getPremium());
        txtDeductible.setText(productinsurance.getDeductible());
        System.out.println("Deductible: "+productinsurance.getDeductible());
        txtBenefits.setText(productinsurance.getBenefits());
        System.out.println("Benefits: "+productinsurance.getBenefits());
        txtPatientID.setText(productpatient.getPatientid());
        System.out.println("Patient ID: "+productpatient.getPatientid());
        txtPrimaryDoctor.setText(productpatient.getPrimarydoctor());
        System.out.println("Primary : "+productpatient.getPrimarydoctor());
        txtLastVisit.setText(productpatient.getLastvisit());
        System.out.println("Last Visit: "+productpatient.getLastvisit());
        txtNextAppointment.setText(productpatient.getNextappointment());
        System.out.println("Next App: "+productpatient.getNextappointment());
        comboAllergies.setSelectedItem(productpatient.getAllergies());
        System.out.println("Allergies: "+productpatient.getAllergies());
        comboOnMedication.setSelectedItem(productpatient.getOnmedication());
        System.out.println("On Medication: "+productpatient.getOnmedication());
        comboInsuranceCoverage.setSelectedItem(productpatient.getInsurancecoverage());
        System.out.println("Insurance Coverage: "+productpatient.getInsurancecoverage());
        
        String imagePathValue = product.getUploadImage();
       
        ImageIcon img = new ImageIcon(imagePathValue);
        Image image1 = img.getImage();
        lblUploadImage.setIcon(new ImageIcon(image1));
    }
}
