/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.ProductDoctor;

/**
 *
 * @author sanal
 */
public class DoctorJPanel extends javax.swing.JPanel {

    ProductDoctor productdoctor;
    /**
     * Creates new form PersonJPanel
     */
    public DoctorJPanel(ProductDoctor productdoctor) {
        initComponents();
        this.productdoctor = productdoctor;
        this.setBackground(new Color(224, 255, 255));
        btnSaveDoctor.setBackground(new Color(0, 128, 255));
        btnSaveDoctor.setForeground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleDoctor = new javax.swing.JLabel();
        lblFirstNameDoctor = new javax.swing.JLabel();
        lblLastNameDoctor = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        lblEducation = new javax.swing.JLabel();
        lblMedicalLicense = new javax.swing.JLabel();
        lblDoctorContact = new javax.swing.JLabel();
        lblPracticeAddress = new javax.swing.JLabel();
        lblYears = new javax.swing.JLabel();
        txtFirstNameDoctor = new javax.swing.JTextField();
        txtLastNameDoctor = new javax.swing.JTextField();
        txtSpecialization = new javax.swing.JTextField();
        txtEducation = new javax.swing.JTextField();
        txtMedicalLicense = new javax.swing.JTextField();
        txtDoctorContact = new javax.swing.JTextField();
        txtPracticeAddress = new javax.swing.JTextField();
        txtYears = new javax.swing.JTextField();
        btnSaveDoctor = new javax.swing.JButton();

        lblTitleDoctor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDoctor.setText("Doctor");

        lblFirstNameDoctor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstNameDoctor.setText("First Name:");

        lblLastNameDoctor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastNameDoctor.setText("Last Name:");

        lblSpecialization.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSpecialization.setText("Specialization:");

        lblEducation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEducation.setText("Education:");

        lblMedicalLicense.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMedicalLicense.setText("Medical License:");

        lblDoctorContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDoctorContact.setText("Doctor Contact:");

        lblPracticeAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPracticeAddress.setText("Practice Address:");

        lblYears.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblYears.setText("Years Of Practice:");

        btnSaveDoctor.setText("Save");
        btnSaveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitleDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLastNameDoctor)
                            .addComponent(lblFirstNameDoctor)
                            .addComponent(lblSpecialization)
                            .addComponent(lblEducation)
                            .addComponent(lblMedicalLicense)
                            .addComponent(lblDoctorContact)
                            .addComponent(lblPracticeAddress)
                            .addComponent(lblYears))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedicalLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoctorContact, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPracticeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(35, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnSaveDoctor)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDoctorContact, lblEducation, lblFirstNameDoctor, lblLastNameDoctor, lblMedicalLicense, lblPracticeAddress, lblSpecialization, lblYears});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstNameDoctor)
                    .addComponent(txtFirstNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastNameDoctor)
                    .addComponent(txtLastNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpecialization)
                    .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEducation)
                    .addComponent(txtEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicalLicense)
                    .addComponent(txtMedicalLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDoctorContact)
                    .addComponent(txtDoctorContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPracticeAddress)
                    .addComponent(txtPracticeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYears)
                    .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveDoctor)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDoctorActionPerformed
        // TODO add your handling code here:
        
        if (txtFirstNameDoctor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "First name cannot be empty!");
            return;
        }
        else {productdoctor.setFirstnamedoctor(txtFirstNameDoctor.getText());}

        if (txtLastNameDoctor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Last name cannot be empty!");
            return;
        }
        else {productdoctor.setLastnamedoctor(txtLastNameDoctor.getText());}
        
        if (txtSpecialization.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Specialization cannot be empty!");
            return;
        }
        else {productdoctor.setSpecialization(txtSpecialization.getText());}
        
        if (txtEducation.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Education cannot be empty!");
            return;
        }
        else {productdoctor.setEducation(txtEducation.getText());}
        
        if (txtMedicalLicense.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Medical license cannot be empty!");
            return;
        }
        else {productdoctor.setMedicallicense(txtMedicalLicense.getText());}
        
        if (txtDoctorContact.getText().trim().isEmpty() || txtDoctorContact.getText().trim().length() != 10) {
            JOptionPane.showMessageDialog(this, "Invalid doctor contact number!");
            return;
        }
        else {productdoctor.setDoctorcontact(txtDoctorContact.getText());}
        
        if (txtPracticeAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Practice address cannot be empty!");
            return;
        }
        else {productdoctor.setPracticeaddress(txtPracticeAddress.getText());}
        
        if (txtYears.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Years of practice cannot be empty!");
            return;
        }
        else {productdoctor.setYears(txtYears.getText());}
        
        
        JOptionPane.showMessageDialog(this, "Doctor Information Saved!");

    }//GEN-LAST:event_btnSaveDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDoctor;
    private javax.swing.JLabel lblDoctorContact;
    private javax.swing.JLabel lblEducation;
    private javax.swing.JLabel lblFirstNameDoctor;
    private javax.swing.JLabel lblLastNameDoctor;
    private javax.swing.JLabel lblMedicalLicense;
    private javax.swing.JLabel lblPracticeAddress;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblTitleDoctor;
    private javax.swing.JLabel lblYears;
    private javax.swing.JTextField txtDoctorContact;
    private javax.swing.JTextField txtEducation;
    private javax.swing.JTextField txtFirstNameDoctor;
    private javax.swing.JTextField txtLastNameDoctor;
    private javax.swing.JTextField txtMedicalLicense;
    private javax.swing.JTextField txtPracticeAddress;
    private javax.swing.JTextField txtSpecialization;
    private javax.swing.JTextField txtYears;
    // End of variables declaration//GEN-END:variables
}
