/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import model.ProductDriver;
import javax.swing.JOptionPane;


/**
 *
 * @author sanal
 */
public class DriverJPanel extends javax.swing.JPanel {
    
    ProductDriver productdriver;

    /**
     * Creates new form PersonJPanel
     */
    public DriverJPanel(ProductDriver productdriver) {
        initComponents();
        this.productdriver = productdriver;
        this.setBackground(new Color(224, 255, 255));
        btnSaveDriver.setBackground(new Color(0, 128, 255));
        btnSaveDriver.setForeground(Color.WHITE);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleDriver = new javax.swing.JLabel();
        lblDriverLicense = new javax.swing.JLabel();
        txtDriverLicense = new javax.swing.JTextField();
        btnSaveDriver = new javax.swing.JButton();

        lblTitleDriver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleDriver.setText("Driver");

        lblDriverLicense.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDriverLicense.setText("Driver License:");

        btnSaveDriver.setText("Save");
        btnSaveDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDriverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitleDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDriverLicense)
                        .addGap(18, 18, 18)
                        .addComponent(txtDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnSaveDriver)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDriverLicense)
                    .addComponent(txtDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveDriver)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDriverActionPerformed
        // TODO add your handling code here:
       
        if (txtDriverLicense.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Driver license cannot be empty!");
            return;
        }

        productdriver.setDriverlicense(txtDriverLicense.getText());

        JOptionPane.showMessageDialog(this, "Driver Information Saved!");
        

    }//GEN-LAST:event_btnSaveDriverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDriver;
    private javax.swing.JLabel lblDriverLicense;
    private javax.swing.JLabel lblTitleDriver;
    private javax.swing.JTextField txtDriverLicense;
    // End of variables declaration//GEN-END:variables
}
