/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import model.ProductInsurance;
import javax.swing.JOptionPane;


/**
 *
 * @author sanal
 */
public class InsuranceJPanel extends javax.swing.JPanel {

    ProductInsurance productinsurance;
    
    /**
     * Creates new form PersonJPanel
     */
    public InsuranceJPanel(ProductInsurance productinsurance) {
        initComponents();
        this.productinsurance = productinsurance;
        this.setBackground(new Color(224, 255, 255));
        btnSaveInsurance.setBackground(new Color(0, 128, 255));
        btnSaveInsurance.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleVehicleRegistration = new javax.swing.JLabel();
        lblCorporateID = new javax.swing.JLabel();
        lblInsuranceAddress = new javax.swing.JLabel();
        lblPremium = new javax.swing.JLabel();
        lblDeductible = new javax.swing.JLabel();
        txtCorporateID = new javax.swing.JTextField();
        txtInsuranceAddress = new javax.swing.JTextField();
        txtPremium = new javax.swing.JTextField();
        txtDeductible = new javax.swing.JTextField();
        btnSaveInsurance = new javax.swing.JButton();
        lblBenefits = new javax.swing.JLabel();
        txtBenefits = new javax.swing.JTextField();

        lblTitleVehicleRegistration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleVehicleRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleVehicleRegistration.setText("Insurance");

        lblCorporateID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCorporateID.setText("Corporate ID:");

        lblInsuranceAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInsuranceAddress.setText("Address:");

        lblPremium.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPremium.setText("Premium:");

        lblDeductible.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDeductible.setText("Deductible:");

        btnSaveInsurance.setText("Save");
        btnSaveInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInsuranceActionPerformed(evt);
            }
        });

        lblBenefits.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBenefits.setText("Benefits:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitleVehicleRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblInsuranceAddress)
                            .addComponent(lblCorporateID)
                            .addComponent(lblPremium)
                            .addComponent(lblDeductible)
                            .addComponent(lblBenefits))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsuranceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeductible, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(55, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnSaveInsurance)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCorporateID, lblDeductible, lblInsuranceAddress, lblPremium});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleVehicleRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorporateID)
                    .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsuranceAddress)
                    .addComponent(txtInsuranceAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremium)
                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeductible)
                    .addComponent(txtDeductible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBenefits)
                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveInsurance)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInsuranceActionPerformed
        // TODO add your handling code here:
        
        
        if (txtCorporateID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Corporate ID cannot be empty!");
            return;
        }
        else {productinsurance.setCorporateid(txtCorporateID.getText());}
        
        if (txtInsuranceAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insurance Address cannot be empty!");
            return;
        }
        else {productinsurance.setInsuranceaddress(txtInsuranceAddress.getText());}
        
        if (txtDeductible.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Deductible cannot be empty!");
            return;
        }
        else {productinsurance.setDeductible(txtDeductible.getText());}
        
        if (txtPremium.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Premium cannot be empty!");
            return;
        }
        else {productinsurance.setPremium(txtPremium.getText());}
        
        if (txtBenefits.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Benefits cannot be empty!");
            return;
        }
        else {productinsurance.setBenefits(txtPremium.getText());}

        JOptionPane.showMessageDialog(this, "Insurance Information Saved!");

    }//GEN-LAST:event_btnSaveInsuranceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveInsurance;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCorporateID;
    private javax.swing.JLabel lblDeductible;
    private javax.swing.JLabel lblInsuranceAddress;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblTitleVehicleRegistration;
    private javax.swing.JTextField txtBenefits;
    private javax.swing.JTextField txtCorporateID;
    private javax.swing.JTextField txtDeductible;
    private javax.swing.JTextField txtInsuranceAddress;
    private javax.swing.JTextField txtPremium;
    // End of variables declaration//GEN-END:variables
}
