/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;
import model.Product;
import model.ProductAddress;
import model.ProductDoctor;
import model.ProductDriver;
import model.ProductVehicleRegistration;
import model.ProductInsurance;
import model.ProductPatient;

public class MainJFrame extends javax.swing.JFrame {

    Product product;
    ProductAddress productaddress;
    ProductDoctor productdoctor;
    ProductDriver productdriver;
    ProductVehicleRegistration productvehicleregistration;
    ProductInsurance productinsurance;
    ProductPatient productpatient;

    public MainJFrame() {
        initComponents();

        controlPanel.setBackground(new Color(173, 216, 230));

        btnPerson.setBackground(new Color(0, 102, 204));
        btnAddress.setBackground(new Color(0, 128, 255));
        btnDriver.setBackground(new Color(0, 102, 204));
        btnVehicleRegistration.setBackground(new Color(0, 128, 255)); 
        btnPatient.setBackground(new Color(0, 102, 204));
        btnDoctor.setBackground(new Color(0, 128, 255));
        btnInsuranceCoverage.setBackground(new Color(0, 102, 204));
        btnDisplay.setBackground(new Color(0, 128, 255));

        btnPerson.setForeground(Color.WHITE);
        btnAddress.setForeground(Color.WHITE);
        btnDriver.setForeground(Color.WHITE);
        btnVehicleRegistration.setForeground(Color.WHITE);
        btnPatient.setForeground(Color.WHITE);
        btnDoctor.setForeground(Color.WHITE);
        btnInsuranceCoverage.setForeground(Color.WHITE);
        btnDisplay.setForeground(Color.WHITE);

        workArea.setBackground(new Color(224, 255, 255));

        product = new Product();
        productaddress = new ProductAddress();
        productdoctor = new ProductDoctor();
        productdriver = new ProductDriver();
        productvehicleregistration = new ProductVehicleRegistration();
        productinsurance = new ProductInsurance();
        productpatient = new ProductPatient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnPerson = new javax.swing.JButton();
        btnAddress = new javax.swing.JButton();
        btnDriver = new javax.swing.JButton();
        btnVehicleRegistration = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnInsuranceCoverage = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPerson.setText("Person");
        btnPerson.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonActionPerformed(evt);
            }
        });

        btnAddress.setText("Address");
        btnAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddressActionPerformed(evt);
            }
        });

        btnDriver.setText("Driver");
        btnDriver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverActionPerformed(evt);
            }
        });

        btnVehicleRegistration.setText("Vehicle Registration");
        btnVehicleRegistration.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVehicleRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicleRegistrationActionPerformed(evt);
            }
        });

        btnPatient.setText("Patient");
        btnPatient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });

        btnDoctor.setText("Doctor");
        btnDoctor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        btnInsuranceCoverage.setText("Insurance Coverage");
        btnInsuranceCoverage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInsuranceCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsuranceCoverageActionPerformed(evt);
            }
        });

        btnDisplay.setText("Display Report");
        btnDisplay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDriver)
                    .addComponent(btnAddress)
                    .addComponent(btnPerson))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDisplay)
                    .addComponent(btnInsuranceCoverage)
                    .addComponent(btnDoctor)
                    .addComponent(btnVehicleRegistration)
                    .addComponent(btnPatient))
                .addContainerGap())
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddress, btnDisplay, btnDoctor, btnDriver, btnInsuranceCoverage, btnPatient, btnPerson, btnVehicleRegistration});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVehicleRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsuranceCoverage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisplay)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddressActionPerformed
        // TODO add your handling code here:
        AddressJPanel createAddressPanel = new AddressJPanel(productaddress);
        splitPane.setRightComponent(createAddressPanel);   
    }//GEN-LAST:event_btnAddressActionPerformed

    private void btnDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverActionPerformed
        // TODO add your handling code here:
        DriverJPanel createDriverPanel = new DriverJPanel(productdriver);
        splitPane.setRightComponent(createDriverPanel);
    }//GEN-LAST:event_btnDriverActionPerformed

    private void btnVehicleRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicleRegistrationActionPerformed
        // TODO add your handling code here:
        VehicleRegistrationJPanel createVehicleRegistrationPanel = new VehicleRegistrationJPanel(productvehicleregistration);
        splitPane.setRightComponent(createVehicleRegistrationPanel);
    }//GEN-LAST:event_btnVehicleRegistrationActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        PatientJPanel createPatientPanel = new PatientJPanel(productpatient);
        splitPane.setRightComponent(createPatientPanel);
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        DoctorJPanel createDoctorPanel = new DoctorJPanel(productdoctor);
        splitPane.setRightComponent(createDoctorPanel);   
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnInsuranceCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsuranceCoverageActionPerformed
        // TODO add your handling code here:
        InsuranceJPanel createInsurancePanel = new InsuranceJPanel(productinsurance);
        splitPane.setRightComponent(createInsurancePanel);
    }//GEN-LAST:event_btnInsuranceCoverageActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        
        DisplayReportJPanel displayReportPanel = new DisplayReportJPanel(product,productaddress,productdoctor,productdriver,productvehicleregistration,productinsurance,productpatient);
        splitPane.setRightComponent(displayReportPanel);
        
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonActionPerformed
        // TODO add your handling code here:
        
        PersonJPanel createPersonPanel = new PersonJPanel(product);
        splitPane.setRightComponent(createPersonPanel);
    }//GEN-LAST:event_btnPersonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddress;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnDriver;
    private javax.swing.JButton btnInsuranceCoverage;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnPerson;
    private javax.swing.JButton btnVehicleRegistration;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
