/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import model.ProductPatient;
import javax.swing.JOptionPane;


/**
 *
 * @author sanal
 */
public class PatientJPanel extends javax.swing.JPanel {

    ProductPatient productpatient;
    
    /**
     * Creates new form PersonJPanel
     */
    public PatientJPanel(ProductPatient productpatient) {
        initComponents();
        this.productpatient = productpatient;
        this.setBackground(new Color(224, 255, 255));
        btnSavePatient.setBackground(new Color(0, 128, 255));
        btnSavePatient.setForeground(Color.WHITE);
        comboAllergies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        comboOnMedication.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        comboInsuranceCoverage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSavePatient = new javax.swing.JButton();
        lblNextAppointment = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        lblOnMedication = new javax.swing.JLabel();
        lblInsuranceCoverage = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtPrimaryDoctor = new javax.swing.JTextField();
        txtLastVisit = new javax.swing.JTextField();
        lblTitlePatient = new javax.swing.JLabel();
        txtNextAppointment = new javax.swing.JTextField();
        lblPatientID = new javax.swing.JLabel();
        lblPrimaryDoctor = new javax.swing.JLabel();
        lblLastVisit = new javax.swing.JLabel();
        comboAllergies = new javax.swing.JComboBox<>();
        comboOnMedication = new javax.swing.JComboBox<>();
        comboInsuranceCoverage = new javax.swing.JComboBox<>();

        btnSavePatient.setText("Save");
        btnSavePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePatientActionPerformed(evt);
            }
        });

        lblNextAppointment.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNextAppointment.setText("Next Appointment:");

        lblAllergies.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAllergies.setText("Allergies?");

        lblOnMedication.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOnMedication.setText("On Medication?");

        lblInsuranceCoverage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblInsuranceCoverage.setText("Insurance Coverage:");

        lblTitlePatient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitlePatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePatient.setText("Patient");

        lblPatientID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPatientID.setText("Patient ID:");

        lblPrimaryDoctor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrimaryDoctor.setText("Primary Doctor:");

        lblLastVisit.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastVisit.setText("Last Visit:");

        comboAllergies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No"}));
        comboAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAllergiesActionPerformed(evt);
            }
        });

        comboOnMedication.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No"}));
        comboOnMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOnMedicationActionPerformed(evt);
            }
        });

        comboInsuranceCoverage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No"}));
        comboInsuranceCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInsuranceCoverageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPrimaryDoctor)
                                            .addComponent(lblPatientID)
                                            .addComponent(lblLastVisit)
                                            .addComponent(lblNextAppointment)
                                            .addComponent(lblAllergies))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPatientID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(txtLastVisit, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(txtNextAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(comboAllergies, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOnMedication)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblTitlePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnSavePatient))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInsuranceCoverage)
                        .addGap(18, 18, 18)
                        .addComponent(comboInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitlePatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrimaryDoctor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastVisit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNextAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNextAppointment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergies)
                    .addComponent(comboAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOnMedication)
                    .addComponent(comboOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsuranceCoverage))
                .addGap(18, 18, 18)
                .addComponent(btnSavePatient)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePatientActionPerformed
        // TODO add your handling code here:
        
        
        if (txtPatientID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Patient ID cannot be empty!");
            return;
        }
        else {productpatient.setPatientid(txtPatientID.getText());}
        
        if (txtPrimaryDoctor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primary Doctor cannot be empty!");
            return;
        }
        else {productpatient.setPrimarydoctor(txtPrimaryDoctor.getText());}
        
        if (txtLastVisit.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Last Visit cannot be empty!");
            return;
        }
        else {productpatient.setLastvisit(txtLastVisit.getText());}
        
        if (txtNextAppointment.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Next Appointment cannot be empty!");
            return;
        }
        else {productpatient.setNextappointment(txtNextAppointment.getText());}
        
        if (comboAllergies.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select an option for Allergies!");
            return;
        }
        else {productpatient.setAllergies(comboAllergies.getSelectedItem().toString());}
        
        if (comboOnMedication.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select an option for On Medication!");
            return;
        }
        else {productpatient.setOnmedication(comboOnMedication.getSelectedItem().toString());}
        
        if (comboInsuranceCoverage.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select an option for Insurance Coverage!");
            return;
        }
        else {productpatient.setInsurancecoverage(comboInsuranceCoverage.getSelectedItem().toString());}

        
        JOptionPane.showMessageDialog(this, "Patient Information Saved!");

    }//GEN-LAST:event_btnSavePatientActionPerformed

    private void comboAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAllergiesActionPerformed

    private void comboOnMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOnMedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOnMedicationActionPerformed

    private void comboInsuranceCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInsuranceCoverageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboInsuranceCoverageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePatient;
    private javax.swing.JComboBox<String> comboAllergies;
    private javax.swing.JComboBox<String> comboInsuranceCoverage;
    private javax.swing.JComboBox<String> comboOnMedication;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblInsuranceCoverage;
    private javax.swing.JLabel lblLastVisit;
    private javax.swing.JLabel lblNextAppointment;
    private javax.swing.JLabel lblOnMedication;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPrimaryDoctor;
    private javax.swing.JLabel lblTitlePatient;
    private javax.swing.JTextField txtLastVisit;
    private javax.swing.JTextField txtNextAppointment;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPrimaryDoctor;
    // End of variables declaration//GEN-END:variables
}
