/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.Product;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.Image;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sanal
 */
public class PersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonJPanel
     */
    
    
    
    Product product;
    
        public PersonJPanel(Product product) {
        initComponents();
        this.product = product;
        this.setBackground(new Color(224, 255, 255));
        btnSavePerson.setBackground(new Color(0, 128, 255));
        btnSavePerson.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitlePerson = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPermAddress = new javax.swing.JLabel();
        lblTempAddress = new javax.swing.JLabel();
        lblOccupation = new javax.swing.JLabel();
        lblNationality = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPermAddress = new javax.swing.JTextField();
        txtTempAddress = new javax.swing.JTextField();
        txtOccupation = new javax.swing.JTextField();
        txtNationality = new javax.swing.JTextField();
        btnSavePerson = new javax.swing.JButton();
        lblPicture = new javax.swing.JLabel();
        lblUploadImage = new javax.swing.JLabel();
        btnUploadImage = new javax.swing.JButton();

        lblTitlePerson.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitlePerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePerson.setText("Person");

        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstName.setText("First Name:");

        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastName.setText("Last Name:");

        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSSN.setText("SSN:");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmail.setText("Email:");

        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDOB.setText("DOB:");

        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone.setText("Phone:");

        lblPermAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPermAddress.setText("Permanent Address:");

        lblTempAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTempAddress.setText("Temporary Address:");

        lblOccupation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOccupation.setText("Occupation:");

        lblNationality.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNationality.setText("Nationality:");

        btnSavePerson.setText("Save");
        btnSavePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePersonActionPerformed(evt);
            }
        });

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPicture.setText("Picture:");

        lblUploadImage.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblUploadImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUploadImage.setText("Upload An Image");
        lblUploadImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnUploadImage.setText("Browse");
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitlePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLastName)
                            .addComponent(lblFirstName)
                            .addComponent(lblSSN)
                            .addComponent(lblEmail)
                            .addComponent(lblDOB)
                            .addComponent(lblPhone)
                            .addComponent(lblPermAddress)
                            .addComponent(lblTempAddress)
                            .addComponent(lblOccupation)
                            .addComponent(lblNationality)
                            .addComponent(lblPicture))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUploadImage, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtPermAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtTempAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtOccupation, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNationality, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnSavePerson)
                            .addComponent(lblUploadImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDOB, lblEmail, lblFirstName, lblLastName, lblNationality, lblOccupation, lblPermAddress, lblPhone, lblSSN, lblTempAddress});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitlePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPermAddress)
                    .addComponent(txtPermAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTempAddress)
                    .addComponent(txtTempAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOccupation)
                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNationality)
                    .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPicture)
                    .addComponent(lblUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUploadImage)
                .addGap(18, 18, 18)
                .addComponent(btnSavePerson)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePersonActionPerformed
        // TODO add your handling code here:
        
    if (txtFirstName.getText() == null || txtFirstName.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "First name cannot be empty");
        return;
    }
    else {product.setFirstname(txtFirstName.getText());}

    if (txtLastName.getText() == null || txtLastName.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Last name cannot be empty");
        return;
    }
    else {product.setLastname(txtLastName.getText());}

    if (txtSSN.getText() == null || txtSSN.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "SSN cannot be empty");
        return;
    }
    product.setSsn(txtSSN.getText());

    if (txtEmail.getText() == null || txtEmail.getText().trim().isEmpty() || !txtEmail.getText().contains("@")) {
        JOptionPane.showMessageDialog(this, "Invalid email");
        return;
    }
    product.setEmail(txtEmail.getText());

    if (txtDOB.getText() == null || txtDOB.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "DOB cannot be empty");
        return;
    }
    product.setDob(txtDOB.getText());

    if (txtPhone.getText() == null || txtPhone.getText().trim().isEmpty() || txtPhone.getText().length() != 10) {
        JOptionPane.showMessageDialog(this, "Invalid phone number");
        return;
    }
    product.setPhone(txtPhone.getName());

    if (txtPermAddress.getText() == null || txtPermAddress.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Permanent address cannot be empty");
        return;
    }
    product.setPermaddress(txtPermAddress.getName());

    if (txtTempAddress.getText() == null || txtTempAddress.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Temporary address cannot be empty");
        return;
    }
    product.setTempaddress(txtTempAddress.getName());

    if (txtOccupation.getText() == null || txtOccupation.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Occupation cannot be empty");
        return;
    }
    product.setOccupation(txtOccupation.getName());

    if (txtNationality.getText() == null || txtNationality.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nationality cannot be empty");
        return;
    }
    product.setNationality(txtNationality.getName());
        
        
        
        JOptionPane.showMessageDialog(this, "Person Information Saved!");
        
        
    }//GEN-LAST:event_btnSavePersonActionPerformed

    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // TODO add your handling code here:
        
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            System.out.println(selectedImagePath);
            JOptionPane.showMessageDialog(null, selectedImagePath);
            
            product.setUploadImage(selectedImagePath);
            System.out.println("displaypath:" + product.getUploadImage());
            ImageIcon ii = new ImageIcon(selectedImagePath);
            Image image1 = ii.getImage().getScaledInstance(lblUploadImage.getWidth(), lblUploadImage.getHeight(), Image.SCALE_SMOOTH);
            lblUploadImage.setIcon(new ImageIcon(image1));
    }//GEN-LAST:event_btnUploadImageActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePerson;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblPermAddress;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTempAddress;
    private javax.swing.JLabel lblTitlePerson;
    private javax.swing.JLabel lblUploadImage;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPermAddress;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTempAddress;
    // End of variables declaration//GEN-END:variables
}
