/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import model.ProductVehicleRegistration;
import javax.swing.JOptionPane;


/**
 *
 * @author sanal
 */
public class VehicleRegistrationJPanel extends javax.swing.JPanel {

    ProductVehicleRegistration productvehicleregistration;
    
    /**
     * Creates new form PersonJPanel
     */
    public VehicleRegistrationJPanel(ProductVehicleRegistration productvehicleregistration) {
        initComponents();
        this.productvehicleregistration = productvehicleregistration;
        this.setBackground(new Color(224, 255, 255));  // Light Cyan
        btnSaveVehicleRegistration.setBackground(new Color(0, 128, 255));  // Another shade of Medical Blue
        btnSaveVehicleRegistration.setForeground(Color.WHITE);  // Text color set to white
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleVehicleRegistration = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        txtExpirationDate = new javax.swing.JTextField();
        btnSaveVehicleRegistration = new javax.swing.JButton();

        lblTitleVehicleRegistration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitleVehicleRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleVehicleRegistration.setText("Vehicle Registration");

        lblModel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblModel.setText("Model:");

        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSerialNumber.setText("Serial Number:");

        lblLicenseNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicenseNumber.setText("License Number:");

        lblExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblExpirationDate.setText("Expiration Date:");

        btnSaveVehicleRegistration.setText("Save");
        btnSaveVehicleRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveVehicleRegistrationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitleVehicleRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSerialNumber)
                            .addComponent(lblModel)
                            .addComponent(lblLicenseNumber)
                            .addComponent(lblExpirationDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btnSaveVehicleRegistration)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblExpirationDate, lblLicenseNumber, lblModel, lblSerialNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleVehicleRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicenseNumber)
                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExpirationDate)
                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnSaveVehicleRegistration)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveVehicleRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveVehicleRegistrationActionPerformed
        // TODO add your handling code here:
        
        if (txtModel.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Model cannot be empty!");
            return;
        }
        else {productvehicleregistration.setModel(txtModel.getText());}
        
        if (txtSerialNumber.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Serial Number cannot be empty!");
            return;
        }
        else {productvehicleregistration.setSerialnumber(txtSerialNumber.getText());}
        
        if (txtLicenseNumber.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "License Number cannot be empty!");
            return;
        }
        else {productvehicleregistration.setLicensenumber(txtLicenseNumber.getText());}
        
        if (txtExpirationDate.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Expiration Date cannot be empty!");
            return;
        }
        else {productvehicleregistration.setExpirationdate(txtExpirationDate.getText());}

        JOptionPane.showMessageDialog(this, "Vehicle Registration Information Saved!");

    }//GEN-LAST:event_btnSaveVehicleRegistrationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveVehicleRegistration;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitleVehicleRegistration;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
